### ISSUE TITLE
Submission via manage.py/django ignores max_machines_count

### ISSUE THREAD

**Issue by 79617261** [cuckoobox/cuckoo#484]
I submitted a file to be run against all machines via the django/manage.py version. It created 3 tasks...and then spun up three machines ignoring my max_machines_count = 1. I am currently running 1.2-dev. I understand this is _dev_ but just incase it wasnt on your radar..

**Comment by jbremer** [comment]
Hi,

This is a race condition in the way that virtual machines are used. The issue lies in the fact that the machine count is fetched based on the state of the machines, however, this state is not updated right away when starting a VM - this happens based on the state reported by the VM manager (e.g., VirtualBox, VMWare, etc..)
I fixed this issue in another repository, focussing on longterm analysis, but didn't really merge the fix upstream - in general I don't have more VMs configured than I want to run at once, so.. :)

See the following two commits for inspiration.. at this point I can't really give you an ETA, sorry for that.
https://github.com/jbremer/longcuckoo/commit/4190c405bcaf7e4d2e5a6c28d630978c1b7a6517
https://github.com/jbremer/longcuckoo/commit/2d4a95624010207c3ff2be9331b68c299ee6fd91

Jurriaan

**Comment by jbremer** [comment]
This issue has been resolved a while ago, closing the issue.

Thanks for reporting :)
