### ISSUE TITLE
Django Interface (Apache) - Behavioral Analysis Tab Not Functioning Correctly

### ISSUE THREAD

**Issue by landw1re** [cuckoobox/cuckoo#537]
I have the Django interface being presented via Apache WSGI and everything seems to be working fine with the exception of the Behavioral Analysis tab.

At first load of that tab everything is there (analysis wise). The problem is when you click any of the color coated icons other than the gray **default** one I receive the following error.

**"Error loading data. Please reload the page and if the error persists contact us."**

Are you by chance using Apache to serve up the Django interface? Would you mind sharing your **<VirtualHost>** config?

**Comment by brad-accuvant** [comment]
This issue can be closed -- Cuckoo is not affected, it was due to a modification of mine.  If you're submitting bugreports to the unmodified version of Cuckoo, *please* make sure you're actually testing against their version.  Nobody likes to receive bug reports for bugs that aren't theirs.

Thanks,
-Brad

**Comment by landw1re** [comment]
Thanks Brad, I wasn't sure if it was a core cuckoo/django related issure or not. I'll be sure to validate before submitting issues going forward. Appreciate you keeping me honest :-)

- Issue is resolved.
